version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: jukebox-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jukebox_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "13306:3306"
